"""Execution engine for running execution plans step-by-step.

This module provides the ExecutionEngine that executes plans generated by
the TaskPlanner, with progress tracking, error handling, and dependency management.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Callable
from enum import Enum
import time
import logging

from .task_planner import ExecutionPlan, PlanStep
from .task_analyzer import TaskAnalysis, TaskComplexity
from .verification_layer import VerificationLayer, VerificationResult
from .file_state_tracker import FileStateTracker
from .rollback_engine import RollbackEngine, RollbackResult

logger = logging.getLogger(__name__)


@dataclass
class StepResult:
    """Result of executing a single plan step.

    Attributes:
        step_id: ID of the executed step
        success: Whether execution succeeded
        tool_used: Name of tool that was executed
        output: Output from tool execution
        error: Error message if failed
        duration: Execution time in seconds
        metadata: Additional execution metadata
    """

    step_id: int
    success: bool
    tool_used: Optional[str] = None
    output: Optional[str] = None
    error: Optional[str] = None
    duration: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        """Human-readable representation."""
        status = "✅ SUCCESS" if self.success else "❌ FAILED"
        time_str = f"{self.duration:.2f}s"

        if self.success:
            return f"Step {self.step_id}: {status} ({time_str}) - {self.tool_used}"
        else:
            return f"Step {self.step_id}: {status} ({time_str}) - {self.error}"


@dataclass
class ExecutionResult:
    """Result of executing a complete execution plan.

    Attributes:
        plan: The execution plan that was executed
        step_results: Results from each step execution
        summary: Human-readable execution summary
        success: Whether all steps succeeded
        completed_steps: IDs of successfully completed steps
        failed_steps: IDs of failed steps
        skipped_steps: IDs of skipped steps
        execution_time: Total execution time in seconds
    """

    plan: ExecutionPlan
    step_results: List[StepResult]
    summary: str
    success: bool
    completed_steps: List[int] = field(default_factory=list)
    failed_steps: List[int] = field(default_factory=list)
    skipped_steps: List[int] = field(default_factory=list)
    execution_time: float = 0.0


class ExecutionEngine:
    """Executes execution plans with progress tracking and error handling.

    The ExecutionEngine takes plans from the TaskPlanner and executes them
    step-by-step, respecting dependencies, handling errors, and providing
    progress updates.
    """

    def __init__(
        self,
        tool_executor,
        llm_backend=None,
        progress_callback: Optional[Callable[[int, str, str], None]] = None,
        enable_verification: bool = True,
        enable_rollback: bool = True
    ):
        """Initialize execution engine.

        Args:
            tool_executor: ToolExecutor instance for running tools
            llm_backend: Optional LLM backend (for future LLM-driven execution)
            progress_callback: Optional callback for progress updates.
                             Callback signature: (step_id, status, message)
                             where step_id=0 for general messages
            enable_verification: Whether to enable post-execution verification
            enable_rollback: Whether to enable automatic rollback on verification failure
        """
        self.tools = tool_executor
        self.llm = llm_backend
        # Wrap default print to match 3-parameter signature
        self.progress_callback = progress_callback or (lambda step_id, status, msg: print(msg))

        # Initialize verification layer if enabled
        self.verifier = VerificationLayer(show_recommendations=True) if enable_verification else None

        # Initialize rollback system if enabled
        self.enable_rollback = enable_rollback
        if enable_rollback:
            self.state_tracker = FileStateTracker()
            self.rollback_engine = RollbackEngine(self.state_tracker)
        else:
            self.state_tracker = None
            self.rollback_engine = None

        logger.info(f"ExecutionEngine initialized (verification: {enable_verification}, rollback: {enable_rollback})")

    def execute_plan(
        self,
        plan: ExecutionPlan,
        task_analysis: Optional[TaskAnalysis] = None
    ) -> ExecutionResult:
        """Execute a complete execution plan.

        Args:
            plan: ExecutionPlan to execute
            task_analysis: Optional TaskAnalysis for iteration limiting

        Returns:
            ExecutionResult with outcomes
        """
        self.progress_callback(0, "info", f"\n{'='*70}")
        self.progress_callback(0, "info", f"🚀 Starting Execution: {plan.task_description}")
        self.progress_callback(0, "info", f"{'='*70}")
        self.progress_callback(0, "info", f"Total Steps: {len(plan.steps)}")
        self.progress_callback(0, "info", f"Risk Level: {plan.overall_risk.upper()}")
        self.progress_callback(0, "info", f"{'='*70}\n")

        start_time = time.time()
        completed = set()
        failed = set()
        skipped = set()
        results = []

        # Get iteration limit based on complexity (ChatGPT Fix #1)
        max_iterations = self._get_iteration_limit(task_analysis) if task_analysis else 5
        logger.info(f"Iteration limit set to: {max_iterations}")

        # Execute steps in order, respecting dependencies
        for step in plan.steps:
            # Check if this step is ready to execute (dependencies met)
            next_step = plan.get_next_pending_step(completed)

            if next_step is None:
                # No more executable steps
                logger.info("No more executable steps remaining")
                break

            if next_step.id != step.id:
                # This step's dependencies aren't met yet, it will be picked up later
                continue

            # Execute the step
            self.progress_callback(step.id, "info", f"\n{'─'*70}")
            self.progress_callback(step.id, "info", f"Step {step.id}/{len(plan.steps)}: {step.description}")
            self.progress_callback(step.id, "info", f"Action: {step.action_type} | Risk: {step.risk}")
            self.progress_callback(step.id, "info", f"{'─'*70}")

            step.status = "in_progress"
            self.progress_callback(step.id, "starting", f"Starting step {step.id}...")
            result = self._execute_step(step)
            results.append(result)

            if result.success:
                # Verify if enabled and step modifies files
                should_fail_step = False
                if self.verifier and self._should_verify_step(step, result):
                    verification_result = self._verify_step_result(step, result)
                    if verification_result:
                        result.metadata['verification'] = verification_result

                        # Show verification result
                        if not verification_result.passed:
                            self.progress_callback(
                                step.id,
                                "warning",
                                f"⚠️  Verification found {len(verification_result.errors)} error(s), "
                                f"{len(verification_result.warnings)} warning(s)"
                            )

                            # Rollback if enabled and verification failed
                            if self.enable_rollback and self.rollback_engine:
                                self.progress_callback(step.id, "warning", "🔄 Rolling back failed step...")
                                rollback_result = self.rollback_engine.rollback_step(step.id)
                                result.metadata['rollback'] = rollback_result

                                if rollback_result.success:
                                    self.progress_callback(
                                        step.id,
                                        "info",
                                        f"✅ {rollback_result}"
                                    )
                                else:
                                    self.progress_callback(
                                        step.id,
                                        "error",
                                        f"❌ {rollback_result}"
                                    )

                                # Mark step as failed due to verification failure (only if rollback enabled)
                                result.success = False
                                result.error = f"Verification failed: {len(verification_result.errors)} error(s)"
                                should_fail_step = True

                # Mark step status based on verification and rollback
                if should_fail_step:
                    # Verification failed and rollback is enabled - fail the step
                    step.status = "failed"
                    step.result = result.error
                    failed.add(step.id)
                    self.progress_callback(step.id, "failed", f"Step {step.id} failed verification")
                else:
                    # Step completed (verification passed, or failed but rollback disabled)
                    step.status = "completed"
                    step.result = result.output
                    completed.add(step.id)
                    self.progress_callback(step.id, "completed", f"Step {step.id} completed ({result.duration:.2f}s)")
            else:
                step.status = "failed"
                step.result = result.error
                failed.add(step.id)
                self.progress_callback(step.id, "failed", f"Step {step.id} failed: {result.error}")

                # Decide whether to continue or abort
                if self._should_abort(plan, step, result):
                    self.progress_callback(0, "error", f"\n🛑 Aborting execution due to critical failure")
                    logger.warning(f"Execution aborted at step {step.id}")
                    # Mark remaining steps as skipped
                    for remaining_step in plan.steps:
                        if remaining_step.id not in completed and remaining_step.id not in failed:
                            remaining_step.status = "skipped"
                            skipped.add(remaining_step.id)
                            self.progress_callback(remaining_step.id, "skipped", f"Step {remaining_step.id} skipped")
                    break
                else:
                    self.progress_callback(step.id, "warning", f"Continuing despite failure (non-critical)")
                    logger.info(f"Continuing after non-critical failure in step {step.id}")

        # Calculate total execution time
        execution_time = time.time() - start_time

        # Generate summary
        summary = self._generate_summary(plan, results, execution_time)

        # Determine overall success
        overall_success = len(failed) == 0 and len(completed) > 0

        return ExecutionResult(
            plan=plan,
            step_results=results,
            summary=summary,
            success=overall_success,
            completed_steps=sorted(list(completed)),
            failed_steps=sorted(list(failed)),
            skipped_steps=sorted(list(skipped)),
            execution_time=execution_time
        )

    def _execute_step(self, step: PlanStep) -> StepResult:
        """Execute a single plan step.

        Args:
            step: PlanStep to execute

        Returns:
            StepResult with outcome
        """
        start_time = time.time()

        try:
            # Map action type to tool name
            tool_name = self._map_action_to_tool(step.action_type, step)

            if not tool_name:
                return StepResult(
                    step_id=step.id,
                    success=False,
                    error=f"No tool mapping found for action type: {step.action_type}",
                    duration=time.time() - start_time
                )

            # Check if tool exists
            if tool_name not in self.tools.tools:
                return StepResult(
                    step_id=step.id,
                    success=False,
                    tool_used=tool_name,
                    error=f"Tool '{tool_name}' not available",
                    duration=time.time() - start_time
                )

            # Capture file state before modification (if rollback enabled)
            if self.enable_rollback and self.state_tracker:
                if self._is_file_modifying_step(step):
                    file_path = step.arguments.get('file_path')
                    if file_path:
                        self.state_tracker.set_step(step.id)
                        state = self.state_tracker.capture_state(file_path)
                        logger.debug(f"Captured state for {file_path} before step {step.id}")

            # Validate tool arguments before execution
            validation_error = self._validate_tool_arguments(tool_name, step.arguments)
            if validation_error:
                logger.warning(f"Skipping step {step.id}: {validation_error}")
                return StepResult(
                    step_id=step.id,
                    success=False,
                    tool_used=tool_name,
                    error=f"[SKIPPED] {validation_error}. This usually means the plan is too abstract. Consider using direct execution mode.",
                    duration=time.time() - start_time
                )

            # Execute the tool
            logger.info(f"Executing tool: {tool_name} with args: {step.arguments}")
            tool_result = self.tools.execute_tool(tool_name, **step.arguments)

            if tool_result.is_success():
                return StepResult(
                    step_id=step.id,
                    success=True,
                    tool_used=tool_name,
                    output=tool_result.output if isinstance(tool_result.output, str) else str(tool_result.output),
                    duration=time.time() - start_time,
                    metadata=tool_result.metadata
                )
            else:
                return StepResult(
                    step_id=step.id,
                    success=False,
                    tool_used=tool_name,
                    error=tool_result.error or "Tool execution failed",
                    duration=time.time() - start_time,
                    metadata=tool_result.metadata
                )

        except Exception as e:
            logger.error(f"Exception executing step {step.id}: {e}", exc_info=True)
            return StepResult(
                step_id=step.id,
                success=False,
                error=f"Exception during execution: {str(e)}",
                duration=time.time() - start_time
            )

    def _map_action_to_tool(self, action_type: str, step: PlanStep) -> Optional[str]:
        """Map action type to tool name.

        Args:
            action_type: The action type from the step
            step: The complete step (in case tool is explicitly specified)

        Returns:
            Tool name or None if no mapping exists
        """
        # If tool is explicitly specified in step, use it
        if step.tool:
            return step.tool

        # Otherwise, map action type to default tool
        mapping = {
            # File operations
            "read": "read_file",
            "write": "write_file",
            "edit": "edit_file",
            "list": "list_directory",

            # Code operations
            "search": "search_code",
            "analyze": "analyze_code",

            # System operations
            "run": "run_command",

            # Git operations
            "git": "git_status",
            "git_status": "git_status",
            "git_diff": "git_diff",
            "git_commit": "git_commit",

            # Verification
            "verify": "analyze_code"   # Use analyze as verification for now
        }

        return mapping.get(action_type)

    def _validate_tool_arguments(self, tool_name: str, arguments: Dict[str, Any]) -> Optional[str]:
        """Validate that required arguments are present for a tool.

        Args:
            tool_name: Name of the tool to execute
            arguments: Arguments provided for the tool

        Returns:
            Error message if validation fails, None if valid
        """
        # Define required arguments for each tool
        required_args = {
            "read_file": ["file_path"],
            "write_file": ["file_path", "content"],
            "edit_file": ["file_path", "old_content", "new_content"],
            "search_code": ["pattern"],
            "analyze_code": ["file_path"],
            "run_command": ["command"],
            "git_commit": ["message"],
            "list_directory": ["directory_path"],
        }

        # Get required arguments for this tool
        required = required_args.get(tool_name, [])

        # Check if all required arguments are present and non-empty
        missing = []
        for arg in required:
            if arg not in arguments or arguments[arg] in [None, "", []]:
                missing.append(arg)

        if missing:
            return f"Missing required arguments for {tool_name}: {', '.join(missing)}"

        return None

    def _get_iteration_limit(self, task_analysis: Optional[TaskAnalysis]) -> int:
        """Get iteration limit based on task complexity.

        This implements ChatGPT Feedback Fix #1: Adaptive iteration limiting
        based on complexity to prevent infinite loops while allowing complex
        tasks sufficient iterations.

        Args:
            task_analysis: Task analysis with complexity information

        Returns:
            Maximum iterations allowed
        """
        if not task_analysis:
            return 5  # Default moderate limit

        # Map complexity to iteration limit
        complexity_map = {
            TaskComplexity.TRIVIAL: 3,
            TaskComplexity.SIMPLE: 3,
            TaskComplexity.MODERATE: 5,
            TaskComplexity.COMPLEX: 8,
            TaskComplexity.VERY_COMPLEX: 10
        }

        return complexity_map.get(task_analysis.complexity, 5)

    def _should_abort(
        self,
        plan: ExecutionPlan,
        failed_step: PlanStep,
        result: StepResult
    ) -> bool:
        """Decide whether execution should abort after a step failure.

        Abort conditions:
        1. Step is high risk and failed
        2. Other steps depend on this step
        3. Step is non-reversible and failed

        Args:
            plan: The execution plan
            failed_step: The step that failed
            result: The failure result

        Returns:
            True if execution should abort, False to continue
        """
        # Condition 1: High risk steps must succeed
        if failed_step.risk == "high":
            logger.info(f"Aborting due to high-risk step {failed_step.id} failure")
            return True

        # Condition 2: Check if other steps depend on this one
        dependent_steps = [
            s for s in plan.steps
            if failed_step.id in s.dependencies
        ]
        if dependent_steps:
            logger.info(
                f"Aborting because {len(dependent_steps)} steps depend on "
                f"failed step {failed_step.id}"
            )
            return True

        # Condition 3: Non-reversible steps must succeed
        if not failed_step.reversible:
            logger.info(f"Aborting due to non-reversible step {failed_step.id} failure")
            return True

        # Otherwise, continue execution
        return False

    def _is_file_modifying_step(self, step: PlanStep) -> bool:
        """Check if a step modifies files.

        Args:
            step: The step to check

        Returns:
            True if step modifies files
        """
        file_modifying_actions = ['write', 'edit', 'write_file', 'edit_file']
        return step.action_type in file_modifying_actions

    def _should_verify_step(self, step: PlanStep, result: StepResult) -> bool:
        """Determine if a step should be verified.

        Args:
            step: The executed step
            result: The step result

        Returns:
            True if verification should run
        """
        # Only verify file modification steps
        return self._is_file_modifying_step(step)

    def _verify_step_result(self, step: PlanStep, result: StepResult) -> Optional[VerificationResult]:
        """Verify the result of a step.

        Args:
            step: The executed step
            result: The step result

        Returns:
            VerificationResult if verification was performed, None otherwise
        """
        try:
            # Extract file path from step arguments
            file_path = step.arguments.get('file_path')
            if not file_path:
                logger.debug(f"No file_path in step {step.id} arguments, skipping verification")
                return None

            # Run verification
            logger.info(f"Verifying file: {file_path}")
            self.progress_callback(step.id, "info", f"🔍 Verifying {file_path}...")

            verification_result = self.verifier.verify_file(file_path)

            # Log results
            if verification_result.passed:
                logger.info(f"Verification passed for {file_path}")
                self.progress_callback(
                    step.id,
                    "info",
                    f"✅ Verification passed (tier {verification_result.tier})"
                )
            else:
                logger.warning(
                    f"Verification failed for {file_path}: "
                    f"{len(verification_result.errors)} errors, "
                    f"{len(verification_result.warnings)} warnings"
                )

            return verification_result

        except Exception as e:
            logger.error(f"Error during verification: {e}", exc_info=True)
            self.progress_callback(
                step.id,
                "warning",
                f"⚠️  Verification error: {str(e)}"
            )
            return None

    def _generate_summary(
        self,
        plan: ExecutionPlan,
        results: List[StepResult],
        execution_time: float
    ) -> str:
        """Generate human-readable execution summary.

        Args:
            plan: The execution plan
            results: Results from all executed steps
            execution_time: Total execution time

        Returns:
            Formatted summary string
        """
        completed = sum(1 for r in results if r.success)
        failed = sum(1 for r in results if not r.success)
        skipped = len(plan.steps) - len(results)
        total_steps = len(plan.steps)

        # Count rollbacks
        rollbacks_attempted = sum(1 for r in results if 'rollback' in r.metadata)
        rollbacks_succeeded = sum(1 for r in results if 'rollback' in r.metadata and r.metadata['rollback'].success)

        # Determine overall status
        if failed == 0 and completed > 0:
            status = "✅ SUCCESS"
            status_emoji = "✅"
        elif completed > 0:
            status = "⚠️  PARTIAL SUCCESS"
            status_emoji = "⚠️"
        else:
            status = "❌ FAILED"
            status_emoji = "❌"

        lines = [
            "",
            "="*70,
            "📊 Execution Summary",
            "="*70,
            "",
            f"**Task:** {plan.task_description}",
            f"**Status:** {status}",
            "",
            f"**Steps:**",
            f"  - Completed: {completed}/{total_steps} {status_emoji}",
            f"  - Failed: {failed}/{total_steps}",
            f"  - Skipped: {skipped}/{total_steps}",
            "",
            f"**Execution Time:** {execution_time:.2f}s",
            ""
        ]

        # Add rollback statistics if any rollbacks occurred
        if rollbacks_attempted > 0:
            lines.extend([
                f"**Rollbacks:**",
                f"  - Attempted: {rollbacks_attempted}",
                f"  - Successful: {rollbacks_succeeded}",
                ""
            ])

        # Add details for failed steps
        if failed > 0:
            lines.extend([
                "### Failed Steps:",
                ""
            ])
            for result in results:
                if not result.success:
                    step = plan.get_step_by_id(result.step_id)
                    if step:
                        lines.append(f"❌ Step {result.step_id}: {step.description}")
                        lines.append(f"   Error: {result.error}")

                        # Add rollback info if available
                        if 'rollback' in result.metadata:
                            rollback = result.metadata['rollback']
                            if rollback.success:
                                lines.append(f"   🔄 Rollback: Successful ({rollback.method})")
                            else:
                                lines.append(f"   🔄 Rollback: Failed - {', '.join(rollback.errors)}")

                        lines.append("")

        # Add success criteria if available
        if plan.success_criteria and completed == total_steps:
            lines.extend([
                "### Success Criteria:",
                ""
            ])
            for criterion in plan.success_criteria:
                lines.append(f"  - {criterion}")
            lines.append("")

        # Add rollback information if there were failures
        if failed > 0 and plan.rollback_strategy:
            lines.extend([
                "### Rollback Strategy:",
                f"  {plan.rollback_strategy}",
                ""
            ])

        lines.append("="*70)

        return "\n".join(lines)
